-- FINANZAS B2.29 — MOVIMIENTOS DE FONDOS / TRASLADOS DE LIQUIDEZ
-- Ejecutar una sola vez en Supabase SQL Editor.
-- No crea ingresos ni gastos. Registra una transferencia interna y ajusta
-- exclusivamente la ubicación de la liquidez.
--
-- Modelo:
-- efectivo -> cuenta bancaria
-- cuenta bancaria -> efectivo
-- cuenta bancaria -> cuenta bancaria
--
-- Requiere las tablas existentes:
-- cierres_financieros(saldo_efectivo_actual, activo, fecha_corte)
-- cuentas_bancarias(id, saldo_actual, activa)
--
-- La función usa una transacción atómica: si una validación falla,
-- ningún saldo queda parcialmente actualizado.

create table if not exists public.transferencias_fondos (
  id bigint generated by default as identity primary key,
  fecha date not null default current_date,
  origen text not null check (origen in ('efectivo','banco')),
  origen_cuenta_id bigint null references public.cuentas_bancarias(id),
  destino text not null check (destino in ('efectivo','banco')),
  destino_cuenta_id bigint null references public.cuentas_bancarias(id),
  monto numeric(14,2) not null check (monto > 0),
  descripcion text null,
  created_at timestamptz not null default now(),
  constraint transferencias_fondos_ruta_chk
    check (
      (origen='efectivo' and origen_cuenta_id is null)
      or
      (origen='banco' and origen_cuenta_id is not null)
    ),
  constraint transferencias_fondos_destino_chk
    check (
      (destino='efectivo' and destino_cuenta_id is null)
      or
      (destino='banco' and destino_cuenta_id is not null)
    ),
  constraint transferencias_fondos_ruta_distinta_chk
    check (origen <> destino or origen_cuenta_id <> destino_cuenta_id)
);

create index if not exists idx_transferencias_fondos_fecha
  on public.transferencias_fondos(fecha desc);

create or replace function public.transferir_fondos_v1(
  p_origen text,
  p_origen_cuenta_id bigint default null,
  p_destino text default null,
  p_destino_cuenta_id bigint default null,
  p_monto numeric default null,
  p_fecha date default current_date,
  p_descripcion text default null
)
returns public.transferencias_fondos
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_cierre public.cierres_financieros%rowtype;
  v_origen_saldo numeric;
  v_destino_saldo numeric;
  v_row public.transferencias_fondos;
begin
  if p_origen not in ('efectivo','banco') then
    raise exception 'Origen inválido. Usa efectivo o banco.';
  end if;

  if p_destino not in ('efectivo','banco') then
    raise exception 'Destino inválido. Usa efectivo o banco.';
  end if;

  if p_origen = p_destino
     and coalesce(p_origen_cuenta_id,-1)=coalesce(p_destino_cuenta_id,-1) then
    raise exception 'El origen y destino no pueden ser iguales.';
  end if;

  if p_monto is null or p_monto <= 0 then
    raise exception 'El monto debe ser mayor que cero.';
  end if;

  if p_origen='banco' and p_origen_cuenta_id is null then
    raise exception 'Falta la cuenta bancaria de origen.';
  end if;

  if p_destino='banco' and p_destino_cuenta_id is null then
    raise exception 'Falta la cuenta bancaria de destino.';
  end if;

  if p_origen='efectivo' and p_origen_cuenta_id is not null then
    raise exception 'El efectivo no utiliza cuenta bancaria de origen.';
  end if;

  if p_destino='efectivo' and p_destino_cuenta_id is not null then
    raise exception 'El efectivo no utiliza cuenta bancaria de destino.';
  end if;

  -- Bloquea el cierre activo para impedir dos traslados simultáneos
  -- que calculen el mismo saldo de efectivo.
  select *
    into v_cierre
  from public.cierres_financieros
  where activo = true
  order by fecha_corte desc
  limit 1
  for update;

  if v_cierre.id is null then
    raise exception 'No existe un cierre financiero activo.';
  end if;

  if p_origen='efectivo' then
    if coalesce(v_cierre.saldo_efectivo_actual,0) < p_monto then
      raise exception 'Fondos insuficientes en efectivo. Disponible: %.', coalesce(v_cierre.saldo_efectivo_actual,0);
    end if;
    update public.cierres_financieros
       set saldo_efectivo_actual = coalesce(saldo_efectivo_actual,0) - p_monto
     where id = v_cierre.id;
  end if;

  if p_destino='efectivo' then
    update public.cierres_financieros
       set saldo_efectivo_actual = coalesce(saldo_efectivo_actual,0) + p_monto
     where id = v_cierre.id;
  end if;

  if p_origen='banco' then
    select saldo_actual
      into v_origen_saldo
    from public.cuentas_bancarias
    where id=p_origen_cuenta_id and activa=true
    for update;

    if not found then
      raise exception 'La cuenta bancaria de origen no existe o está inactiva.';
    end if;

    if coalesce(v_origen_saldo,0) < p_monto then
      raise exception 'Fondos insuficientes en la cuenta de origen. Disponible: %.', coalesce(v_origen_saldo,0);
    end if;

    update public.cuentas_bancarias
       set saldo_actual=coalesce(saldo_actual,0)-p_monto
     where id=p_origen_cuenta_id;
  end if;

  if p_destino='banco' then
    select saldo_actual
      into v_destino_saldo
    from public.cuentas_bancarias
    where id=p_destino_cuenta_id and activa=true
    for update;

    if not found then
      raise exception 'La cuenta bancaria de destino no existe o está inactiva.';
    end if;

    update public.cuentas_bancarias
       set saldo_actual=coalesce(saldo_actual,0)+p_monto
     where id=p_destino_cuenta_id;
  end if;

  insert into public.transferencias_fondos(
    fecha,origen,origen_cuenta_id,destino,destino_cuenta_id,monto,descripcion
  )
  values(
    coalesce(p_fecha,current_date),
    p_origen,p_origen_cuenta_id,
    p_destino,p_destino_cuenta_id,
    p_monto,p_descripcion
  )
  returning * into v_row;

  return v_row;
end;
$$;

grant execute on function public.transferir_fondos_v1(
  text,bigint,text,bigint,numeric,date,text
) to anon, authenticated;

grant select, insert on public.transferencias_fondos to anon, authenticated;

-- Si posteriormente se activa RLS en producción, estas concesiones
-- deben complementarse con políticas por usuario/autenticación.
