-- FINANZAS B2.17 INTEGRADA — MOTOR MULTIFUENTE DE GENERACIÓN DE INGRESOS
-- NO crea ni modifica jornadas_financieras.
-- NO elimina datos históricos.

create table if not exists public.fuentes_ingreso (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  tipo text not null check (tipo in ('plataforma','servicio','emprendimiento','ecommerce','otro')),
  activa boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.generacion_ingresos (
  id bigint generated by default as identity primary key,
  fuente_id bigint not null references public.fuentes_ingreso(id),
  actividad text not null,
  descripcion text,
  cliente text,
  fecha_generacion date not null,
  fecha_cobro date,
  monto_bruto numeric(12,2) not null default 0 check (monto_bruto >= 0),
  costos numeric(12,2) not null default 0 check (costos >= 0),
  comisiones numeric(12,2) not null default 0 check (comisiones >= 0),
  monto_neto numeric(12,2) generated always as (greatest(monto_bruto-costos-comisiones,0)) stored,
  estado_cobro text not null default 'pendiente' check (estado_cobro in ('pendiente','cobrado','cancelado')),
  movimiento_id bigint references public.movimientos(id),
  notas text,
  created_at timestamptz not null default now()
);

create index if not exists generacion_ingresos_fecha_idx on public.generacion_ingresos(fecha_generacion);
create index if not exists generacion_ingresos_cobro_idx on public.generacion_ingresos(fecha_cobro);
create index if not exists generacion_ingresos_fuente_idx on public.generacion_ingresos(fuente_id);

insert into public.fuentes_ingreso (nombre,tipo) values
('Uber / inDrive','plataforma'),
('Servicios independientes','servicio'),
('Somos Software','emprendimiento'),
('E-commerce','ecommerce'),
('Otros ingresos','otro')
on conflict (nombre) do nothing;

alter table public.fuentes_ingreso enable row level security;
alter table public.generacion_ingresos enable row level security;

drop policy if exists "fuentes_ingreso_select" on public.fuentes_ingreso;
create policy "fuentes_ingreso_select" on public.fuentes_ingreso for select to anon, authenticated using (true);
drop policy if exists "fuentes_ingreso_insert" on public.fuentes_ingreso;
create policy "fuentes_ingreso_insert" on public.fuentes_ingreso for insert to anon, authenticated with check (true);
drop policy if exists "fuentes_ingreso_update" on public.fuentes_ingreso;
create policy "fuentes_ingreso_update" on public.fuentes_ingreso for update to anon, authenticated using (true) with check (true);

drop policy if exists "generacion_ingresos_select" on public.generacion_ingresos;
create policy "generacion_ingresos_select" on public.generacion_ingresos for select to anon, authenticated using (true);
drop policy if exists "generacion_ingresos_insert" on public.generacion_ingresos;
create policy "generacion_ingresos_insert" on public.generacion_ingresos for insert to anon, authenticated with check (true);
drop policy if exists "generacion_ingresos_update" on public.generacion_ingresos;
create policy "generacion_ingresos_update" on public.generacion_ingresos for update to anon, authenticated using (true) with check (true);
