-- FINANZAS V2.3.3
-- Cuentas bancarias + Cero Financiero + datos iniciales verificables.
-- NO elimina movimientos, compromisos ni historial.

begin;

create table if not exists public.cuentas_bancarias (
  id bigint generated by default as identity primary key,
  nombre_banco text not null,
  nombre_cuenta text not null,
  tipo_cuenta text not null default 'Otro',
  identificador text,
  saldo_apertura numeric(14,0) not null default 0,
  saldo_actual numeric(14,0) not null default 0,
  fecha_corte date not null default current_date,
  activa boolean not null default true,
  notas text,
  created_at timestamptz not null default now()
);

create index if not exists idx_cuentas_bancarias_activas on public.cuentas_bancarias(activa);
create index if not exists idx_cuentas_bancarias_banco on public.cuentas_bancarias(nombre_banco);

-- Cero Financiero: 17/09/2026, liquidez de apertura $1.824.
-- Se reutiliza el cierre existente si ya fue creado por B2.1/B2.3.2.
update public.cierres_financieros
set fecha_corte='2026-09-17', saldo_inicial=1824, activo=true
where id=(
  select id from public.cierres_financieros
  order by activo desc, fecha_corte desc, id desc
  limit 1
);

-- Si por alguna razón no existiera ningún cierre, crea uno.
insert into public.cierres_financieros(nombre,fecha_corte,saldo_inicial,activo,notas)
select 'Cero Financiero — 17/09/2026','2026-09-17',1824,true,
       'Apertura operativa: efectivo $50 + BancoEstado $1.500 + Santander $274.'
where not exists (select 1 from public.cierres_financieros);

-- Cuentas conocidas al inicio. Son solo las cuentas con saldo operativo confirmado;
-- el catálogo permite agregar las restantes sin modificar esta arquitectura.
insert into public.cuentas_bancarias
(nombre_banco,nombre_cuenta,tipo_cuenta,saldo_apertura,saldo_actual,fecha_corte,activa,notas)
select 'BancoEstado','Cuenta operativa','Cuenta vista',1500,1500,'2026-09-17',true,
       'Saldo de apertura conocido al Cero Financiero.'
where not exists (
  select 1 from public.cuentas_bancarias
  where lower(nombre_banco)=lower('BancoEstado')
    and lower(nombre_cuenta)=lower('Cuenta operativa')
    and fecha_corte='2026-09-17'
);

insert into public.cuentas_bancarias
(nombre_banco,nombre_cuenta,tipo_cuenta,saldo_apertura,saldo_actual,fecha_corte,activa,notas)
select 'Santander','Cuenta operativa','Cuenta corriente',274,274,'2026-09-17',true,
       'Saldo de apertura conocido al Cero Financiero.'
where not exists (
  select 1 from public.cuentas_bancarias
  where lower(nombre_banco)=lower('Santander')
    and lower(nombre_cuenta)=lower('Cuenta operativa')
    and fecha_corte='2026-09-17'
);

-- Validaciones de seguridad: Santiago debe permanecer una sola vez.
-- Este bloque NO inserta ni elimina Santiago.

commit;

-- =====================
-- VALIDACIÓN POSTERIOR
-- =====================
select count(*) as cantidad_deudas_santiago,
       coalesce(sum(saldo_actual),0) as saldo_santiago
from public.deudas
where lower(trim(acreedor))='santiago';

select id,nombre_banco,nombre_cuenta,saldo_apertura,saldo_actual,fecha_corte,activa
from public.cuentas_bancarias
order by nombre_banco,nombre_cuenta;

select id,nombre,fecha_corte,saldo_inicial,activo
from public.cierres_financieros
where activo=true
order by fecha_corte desc,id desc;
