-- EJECUTAR ESTE SCRIPT COMPLETO EN SUPABASE > SQL EDITOR
create table if not exists movimientos (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('ingreso','gasto')),
  fecha date not null,
  monto numeric(14,0) not null check (monto >= 0),
  categoria text,
  descripcion text,
  created_at timestamptz default now()
);

create table if not exists compromisos (
  id bigint generated by default as identity primary key,
  concepto text not null,
  fecha_vencimiento date not null,
  monto numeric(14,0) not null check (monto >= 0),
  categoria text,
  periodicidad text not null default 'unico' check (periodicidad in ('unico','semanal','mensual','anual')),
  estado text not null default 'pendiente' check (estado in ('pendiente','pagado','cancelado')),
  notas text,
  created_at timestamptz default now()
);

create table if not exists ahorro (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('aporte','retiro')),
  fecha date not null,
  monto numeric(14,0) not null check (monto >= 0),
  descripcion text,
  created_at timestamptz default now()
);

-- Para una V1 personal usada desde tu propio teléfono.
-- Habilitamos acceso mediante la clave anon. Si luego quieres usuarios,
-- añadiremos autenticación y políticas RLS por usuario.
alter table movimientos disable row level security;
alter table compromisos disable row level security;
alter table ahorro disable row level security;
